generate_features: true
preprocess: true
train_model: true
params:
  Si: /home/hyunjin/CLADE/SiO2-x_distillatio/materials-ml-kit/research-sio2-allegro-simplenn-distillation/gpu_return_v5/seed01_bundle_preview/params_Si
  O: /home/hyunjin/CLADE/SiO2-x_distillatio/materials-ml-kit/research-sio2-allegro-simplenn-distillation/gpu_return_v5/seed01_bundle_preview/params_O
neural_network:
  method: Adam
  nodes: 30-30
  batch_size: 2
  total_epoch: 1
  learning_rate: 0.0001
  double_precision: true
  use_force: true
  use_stress: false
  E_loss_type: 1
  F_loss_type: 1
  stress_loss_weight: 0.0
  subprocesses: 0
  accurate_train_rmse: true
  train: true
  test: false
  use_gpu: true
random_seed: 234
data:
  type: symmetry_function
  refdata_format: extxyz
  compress_outcar: false
  struct_list: /tmp/claude-1002/-home-hyunjin-CLADE-SiO2-x-distillatio-materials-ml-kit-paper-sio2-agentic-distillation/192ca6bd-72d4-47f0-b066-84bc7a70e6fa/scratchpad/proj-mad-pydanticai-full-runtime/work/repr_1bjgiia1/out_105/structure_list
  absolute_path: true
  read_force: true
  read_stress: false
preprocessing:
  valid_rate: 0.1
  shuffle: true
